### ISSUE TITLE
Body position sensor reference values

### ISSUE THREAD

**Issue by LucaCerina** [nsrr/wsc-data-dictionary#8]
Hi,
this is slightly unrelated to the data dictionary, but in some cases the annotation files do not contain body position annotations (example visit2-28286).
I have seen the sensor signal is available in the EDF file, but reference voltage for each position are missing...

**Comment by mrueschman** [comment]
Thanks Luca - I dredged up some conversations between the NSRR and WSC about this very topic, however the discussions petered out in 2021. I am going to close the issue here since we would put this sort of information in the WSC documentation. I opened a new issue here and will revisit with the team at some point: https://github.com/nsrr/wsc-documentation/issues/8
